# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: trusty
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:
      - rhaschke@techfak.uni-bielefeld.de
      - me@v4hn.de
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros               UPSTREAM_WORKSPACE=.rosinstall
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed  UPSTREAM_WORKSPACE=.rosinstall
    - ROS_DISTRO=melodic  ROS_REPO=ros               UPSTREAM_WORKSPACE=.rosinstall
    - ROS_DISTRO=melodic  ROS_REPO=ros-shadow-fixed  UPSTREAM_WORKSPACE=.rosinstall

before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
  - . .prepare_overlay.sh

script:
  - .moveit_ci/travis.sh
